# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: VSCodium.VSCodium
PackageVersion: 1.84.0.23306
PackageLocale: en-US
Publisher: VSCodium
PublisherUrl: https://github.com/VSCodium/vscodium
PublisherSupportUrl: https://github.com/VSCodium/vscodium/issues
Author: VSCodium
PackageName: VSCodium
PackageUrl: https://vscodium.com
License: MIT
LicenseUrl: https://github.com/VSCodium/vscodium/blob/master/LICENSE
Copyright: Copyright (c) 2022 VSCodium Team
CopyrightUrl: https://github.com/VSCodium/vscodium/blob/master/LICENSE
ShortDescription: VSCodium is a community-driven, freely-licensed and telemetry-free rebuilt of Microsoft's Visual Studio Code.
Description: |-
  VSCodium is a community-driven, freely-licensed and telemetry-free rebuilt of Microsoft's Visual Studio Code.
  VSCodium is a powerful IDE which runs on your desktop and is available for Windows, macOS and Linux.
Tags:
- cross-platform
- editor
- foss
- ide
- javascript
- open-source
- typescript
- vscode
ReleaseNotes: |-
  What's Changed
  - [WIP] fix(insiders): windows by @daiyam in #1690
  - Fix typo Docs.md by @Ahhj93 in #1679
  - feat: prepare for 1.85 by @daiyam in #1706
  - fix: always add platform info for windows by @daiyam in #1707
  - docs: add troubleshooting link and CONTRIBUTING.md by @daiyam in #1705
  - feat: disable cloud by @daiyam in #1709
  New Contributors
  - @Ahhj93 made their first contribution in #1679
ReleaseNotesUrl: https://github.com/VSCodium/vscodium/releases/tag/1.84.0.23306
ManifestType: defaultLocale
ManifestVersion: 1.5.0
