# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: VSCodium.VSCodium
PackageVersion: 1.84.0.23306
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /mergetasks=!runcode
UpgradeBehavior: install
ReleaseDate: 2023-11-02
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.84.0.23306/VSCodiumUserSetup-arm64-1.84.0.23306.exe
  InstallerSha256: 1E72B9AF21999EBF2C14A6B635FF6E8B275EC4400977F6507174B97EED8D7A74
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.84.0.23306/VSCodiumSetup-x64-1.84.0.23306.exe
  InstallerSha256: 92C77E9AAD5ACBA09B3AF52ADD9C89A2B5F35CF9F75ABDC6D23A6A636F68A098
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.84.0.23306/VSCodiumUserSetup-x64-1.84.0.23306.exe
  InstallerSha256: F6B76CE2CDBFDEBF16B42E80B0B848FA6EF3AF7A86597855503AB507E2B91B2F
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.84.0.23306/VSCodiumSetup-x64-1.84.0.23306.exe
  InstallerSha256: 92C77E9AAD5ACBA09B3AF52ADD9C89A2B5F35CF9F75ABDC6D23A6A636F68A098
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.84.0.23306/VSCodiumUserSetup-arm64-1.84.0.23306.exe
  InstallerSha256: 1E72B9AF21999EBF2C14A6B635FF6E8B275EC4400977F6507174B97EED8D7A74
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.84.0.23306/VSCodiumSetup-arm64-1.84.0.23306.exe
  InstallerSha256: B7010C3FA3D43851F5CD445669D8A1F6B2851510935F24D62516E0C5AF2DA3D3
ManifestType: installer
ManifestVersion: 1.5.0
