# Created with WinGet Releaser v2 using Komac v1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: VSCodium.VSCodium
PackageVersion: 1.76.2.23074
MinimumOSVersion: 10.0.0.0
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /mergetasks=!runcode
UpgradeBehavior: install
ReleaseDate: 2023-03-15
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.2.23074/VSCodiumSetup-ia32-1.76.2.23074.exe
  InstallerSha256: A003F1954084B368D1A79740E8CF3F2C1A2C78B5A792AEED99F4BE2DEC528310
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.2.23074/VSCodiumSetup-ia32-1.76.2.23074.exe
  InstallerSha256: A003F1954084B368D1A79740E8CF3F2C1A2C78B5A792AEED99F4BE2DEC528310
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.2.23074/VSCodiumSetup-x64-1.76.2.23074.exe
  InstallerSha256: 774793CECDD54E789DF7CA977DD790484D8E6166BDDE30A48D7E6E904ABB4EF1
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.2.23074/VSCodiumSetup-x64-1.76.2.23074.exe
  InstallerSha256: 774793CECDD54E789DF7CA977DD790484D8E6166BDDE30A48D7E6E904ABB4EF1
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.2.23074/VSCodiumSetup-arm64-1.76.2.23074.exe
  InstallerSha256: 82386F11C77CCF65AD4E4C2E9C719D01C73AA109BD1BEB0A4A61654579C6B673
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/VSCodium/vscodium/releases/download/1.76.2.23074/VSCodiumSetup-arm64-1.76.2.23074.exe
  InstallerSha256: 82386F11C77CCF65AD4E4C2E9C719D01C73AA109BD1BEB0A4A61654579C6B673
ManifestType: installer
ManifestVersion: 1.4.0
